"""
Shared utilities for this SMAIRT project.

As your project grows, extract common patterns into this shared library.
Typical modules:

- logging.py   — TeeLogger for dual console/file output
- metrics.py   — Evaluation metrics used across experiments
- data_loading.py — Data loading and preprocessing functions
- models.py    — Model architectures shared across scripts

Usage from experiment scripts, which run from the project root:
    from scripts.shared import TeeLogger, setup_logging
    from scripts.shared.data_loading import load_data
    from scripts.shared.metrics import compute_score

Scripts generated by `scripts/new_iteration.py` already put the project root on the
path, so these imports resolve wherever the script lives. If you write a script by
hand and an import fails, add the same three lines it uses:
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
"""

from .logging import TeeLogger, setup_logging

__all__ = [
    "TeeLogger",
    "setup_logging",
]
